name: Build

on:
  push:
    paths-ignore:
      - README.md
      - .gitignore
      - .github/**
  pull_request_target:
   
  workflow_dispatch:

  jobs:
    build:
      runs-on: ubuntu-latest

      steps:
      
    
